# Generated by Django 4.2.28 on 2026-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=10),
        ),
    ]
